{% set version = "0.20.3" %}

package:
  name: pytest-asyncio
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pytest-asyncio/pytest-asyncio-{{ version }}.tar.gz
    sha256: 83cbf01169ce3e8eb71c6c278ccb0574d1a7a3bb8eaaf5e50e0ad342afb33b36
  - folder: src
    url: https://github.com/pytest-dev/pytest-asyncio/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 71167da362a2c1ab22a048463eb2954b7f15fba18d41eee6a3b9db03863a2580

build:
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm >=6.2
  run:
    - pytest >=6.1.0
    - python >=3.7
    - typing_extensions >=3.7.2

test:
  source_files:
    - src/tests
    - src/setup.cfg
  imports:
    - pytest_asyncio
  requires:
    - pip
    - coverage
    - hypothesis >=5.7.1
    - pytest-trio
  commands:
    - pip check
    - cd src
    # the skip is for docker network issues in CI, reduces coverage from 96
    - coverage run -m pytest -vv -k 'not (unused_port_fixture or unused_port_factory_fixture or auto_mode_cmdline)'
    - coverage report --fail-under 91

about:
  home: http://github.com/pytest-dev/pytest-asyncio
  license: Apache-2.0
  license_file: dist/LICENSE
  summary: Pytest support for asyncio
  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - sodre
    - bollwyvl
