{% set version = "0.16.0" %}

package:
  name: pytest-asyncio
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pytest-asyncio/pytest-asyncio-{{ version }}.tar.gz
    sha256: 7496c5977ce88c34379df64a66459fe395cd05543f0a2f837016e7144391fcfb
  - folder: src
    url: https://github.com/pytest-dev/pytest-asyncio/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 2cc3c93f340185a9128dc1f3fcf6c57ad0bfb704c5b6ce425a3ab0ddbb875bb9

build:
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytest >=5.4

test:
  source_files:
    - src/tests
  imports:
    - pytest_asyncio
  requires:
    - pip
    - coverage
    - hypothesis >=5.7.1
  commands:
    - pip check
    - cd src
    # the skip is for docker network issues in CI, reduces coverage from 96
    - coverage run -m pytest -vv -k 'not (unused_port_fixture or unused_port_factory_fixture)'
    - coverage report --fail-under 91

about:
  home: http://github.com/pytest-dev/pytest-asyncio
  license: Apache-2.0
  license_file: dist/LICENSE
  summary: Pytest support for asyncio
  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - sodre
    - bollwyvl
